name: e2e-tests-workflow

on: pull_request

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Create .env
        run: |
          touch .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_USER=${{  vars.POSTGRES_USERNAME }}" >> .env
          echo "POSTGRES_DB=${{ vars.POSTGRES_DATABASE }}" >> .env
          echo "BASE_URL_DEV=${{ vars.BASE_URL_DEV }}" >> .env
          echo "BASE_URL_STAGING=${{ vars.BASE_URL_STAGING }}" >> .env
          echo "BASE_URL_PRODUCTION=${{ vars.BASE_URL_PRODUCTION }}" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
          echo "FIXTURES=TRUE" >> .env
      - name: Create e2e .env
        run: |
          cd e2e
          touch .env
          echo "TEST_MAIL_API_KEY=${{ secrets.TEST_MAIL_API_KEY }}" >> .env
          echo "TEST_MAIL_NAMESPACE=${{ secrets.TEST_MAIL_NAMESPACE }}" >> .env
      - name: Launch e2e tests
        run: docker compose -f docker-compose.e2e.yml up --build --exit-code-from=e2e
